### PR TITLE
Try to put fish jigsaw chest to empty slot

### PR DESCRIPTION
**Pull request by OmerFI**
This code will try to identify the fish jigsaw chest from the inventory. If found, it will put the chest to the empty slot in the puzzle window.

### CODE REVIEW

**Comment by VladTVZ** [comment]
Hi, can you please make the same thing for the bait (to put new bait in the slot after it's empty) and also make the code to clear the inventory and open the fishes ? I'm trying for more than a week to do this and i have almost 0 progress.
Thx and much appreciated for you work :)

**Comment by OmerFI** [comment]
I am trying the same thing for the bait but it isn't detected very well, I am researching a bit to detect the bait perfectly.

**Comment by VladTVZ** [comment]
Than you verry much, in the meanwhile i will research for inventory clearing maybe i can do something or at least i can help with some research :)

**Comment by VladTVZ** [comment]
Hello guys, i have managed to make the script open the fish and also to put the bait in the slot when it's empty, how can i update the script here on the GitHub ?

**Comment by vncsms** [comment]
You can open a pull request

**Comment by ilahikomediya** [comment]
> Hello guys, i have managed to make the script open the fish and also to put the bait in the slot when it's empty, how can i update the script here on the GitHub ?

Can you please share the updated version of this code you made.

**Pull request merged**
